#!/bin/bash
################################################################################
# 03-skypilot/setup-skypilot.sh
#
# ติดตั้ง SkyPilot + ตั้งค่า ~/.sky/config.yaml ให้ชี้ไป K3s + AWS
#
# Prerequisites:
#   - Python 3.10+ (venv)
#   - AWS credentials ใน credentials.env
#   - kubectl ชี้ไป K3s cluster แล้ว
#   - Terraform apply เสร็จแล้ว (ต้องการ private_subnet_id + sg_spot_workers_id)
#
# Usage:
#   source credentials.env
#   bash 03-skypilot/setup-skypilot.sh
################################################################################
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "════════════════════════════════════════════════════════════"
echo "  VirtualLab — SkyPilot Setup"
echo "════════════════════════════════════════════════════════════"
echo ""

# ── Validate required env vars ───────────────────────────────────────────────
REQUIRED_VARS=(
    "AWS_ACCESS_KEY_ID"
    "AWS_SECRET_ACCESS_KEY"
    "AWS_DEFAULT_REGION"
    "ML_BUCKET_NAME"
)
MISSING=()
for var in "${REQUIRED_VARS[@]}"; do
    val="${!var:-}"
    if [[ -z "$val" || "$val" == *"REPLACE_ME"* ]]; then
        MISSING+=("$var")
    fi
done
if [ ${#MISSING[@]} -gt 0 ]; then
    echo "❌ Missing credentials:"
    for v in "${MISSING[@]}"; do echo "   • $v"; done
    echo "   source credentials.env then re-run."
    exit 1
fi

# ── 1. Install SkyPilot in a venv ────────────────────────────────────────────
VENV_DIR="$HOME/skypilot-venv"
echo "→ Setting up SkyPilot venv at $VENV_DIR..."

if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
pip install --upgrade pip --quiet
pip install "skypilot[aws,kubernetes]" --quiet
echo "✅ SkyPilot installed: $(sky --version)"

# ── 2. Configure AWS credentials for SkyPilot ────────────────────────────────
echo ""
echo "→ Configuring AWS credentials..."
mkdir -p ~/.aws
cat > ~/.aws/credentials <<EOF
[default]
aws_access_key_id = ${AWS_ACCESS_KEY_ID}
aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
EOF
cat > ~/.aws/config <<EOF
[default]
region = ${AWS_DEFAULT_REGION}
output = json
EOF
echo "✅ AWS credentials written to ~/.aws/"

# ── 3. Read Terraform outputs for subnet/SG IDs ──────────────────────────────
echo ""
echo "→ Reading Terraform outputs..."
TF_DIR="$REPO_ROOT/01-terraform"
PRIVATE_SUBNET_ID=$(terraform -chdir="$TF_DIR" output -raw private_subnet_id 2>/dev/null || echo "")
SG_SPOT_WORKERS_ID=$(terraform -chdir="$TF_DIR" output -raw sg_spot_workers_id 2>/dev/null || echo "")

if [[ -z "$PRIVATE_SUBNET_ID" ]]; then
    echo "⚠️  Could not read private_subnet_id from Terraform."
    echo "   Run: cd 01-terraform && terraform apply"
    echo "   Then re-run this script."
    echo ""
    echo "   Setting placeholder — sky_config.yaml will need manual update."
    PRIVATE_SUBNET_ID="subnet-REPLACE_ME"
    SG_SPOT_WORKERS_ID="sg-REPLACE_ME"
else
    echo "   private_subnet_id:  $PRIVATE_SUBNET_ID"
    echo "   sg_spot_workers_id: $SG_SPOT_WORKERS_ID"
fi

# ── 4. Write ~/.sky/config.yaml ──────────────────────────────────────────────
echo ""
echo "→ Writing ~/.sky/config.yaml..."
mkdir -p ~/.sky
cat > ~/.sky/config.yaml <<EOF
# VirtualLab SkyPilot Global Config
# Auto-generated by 03-skypilot/setup-skypilot.sh
# Regenerate by re-running that script after Terraform apply.

aws:
  vpc_name: virtuallab-vpc

  # CONSTRAINT #4: Spot workers ONLY in private subnet (no public IP)
  # Value from: terraform output -raw private_subnet_id
  subnets:
    - ${PRIVATE_SUBNET_ID}

  # Only use the SG that allows SSH from Tailscale gateway only
  security_group_name: virtuallab-sg-spot-workers

  # Private IPs only — SSH routed via Tailscale → t4g.nano → private IP
  use_internal_ips: true

kubernetes:
  # Use portforward — works without NodePort or LoadBalancer
  networking: portforward

# Logs stored locally during POC
log_dir: /tmp/sky_logs
EOF
echo "✅ ~/.sky/config.yaml written"

# ── 5. Verify setup ──────────────────────────────────────────────────────────
echo ""
echo "→ Running sky check..."
sky check
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✅ SkyPilot ready!"
echo ""
echo "Next steps:"
echo "  # Test K3s branch (on-prem only):"
echo "  sky launch 03-skypilot/task-k3s-test.yaml"
echo ""
echo "  # Test AWS branch (Spot only):"
echo "  sky launch 03-skypilot/task-aws-burst.yaml"
echo ""
echo "  # Test 2-tier auto routing:"
echo "  sky launch 03-skypilot/task-2tier.yaml"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  Remember to activate the venv in future sessions:"
echo "   source $VENV_DIR/bin/activate"
