all:
  children:
    master:
      hosts:
        virtual-lab-master:
          ansible_host: 100.106.139.119

    skypilot_nodes:
      hosts:
        skypilot-node-01:
          ansible_host: 100.110.215.53

#    registry_host:
#      hosts:
#        virtual-lab-registry_host:
#          ansible_host: #Placeholder
