- name: Provision Virtual-Lab master
  hosts: master
  become: yes
  roles:
    - { role: common, tags: ['common'] }
    - { role: tailscale, tags: ['tailscale'] }
    - { role: k3s-server, tags: ['k3s-server'] }
    - { role: skypilot-node, tags: ['skypilot-node'] }