---
- name: Read node token from artifacts
  ansible.builtin.set_fact:
    k3s_token: "{{ lookup('file', playbook_dir + '/artifacts/node-token') }}"

- name: Get master node IP from inventory
  ansible.builtin.set_fact:
    k3s_master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"

- name: Install K3s agent
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | \
      INSTALL_K3S_VERSION={{ k3s_version }} \
      K3S_URL=https://{{ k3s_master_ip }}:{{ k3s_api_port }} \
      K3S_TOKEN={{ k3s_token }} \
      sh -s - agent \
      --node-ip {{ ansible_host }} \
      --flannel-iface {{ flannel_iface }}
  args:
    creates: /usr/local/bin/k3s-agent

#เช็กว่า host status ขึ้น ready หรือยัง
- name: Check current Ready status of this node in the cluster
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    k3s kubectl get nodes -o wide --no-headers | awk -v ip="{{ ansible_host }}" '$6==ip {print $2}'
  delegate_to: "{{ groups['master'][0] }}"
  vars:
    ansible_become: false
  changed_when: false
  register: node_status


- name: Wait for node to be ready (ข้ามถ้า Ready อยู่แล้ว)
  ansible.builtin.shell: |
    for i in {1..30}; do
      STATUS=$(k3s kubectl get nodes -o wide --no-headers | awk -v ip="{{ ansible_host }}" '$6==ip {print $2}')
      [ "$STATUS" = "Ready" ] && exit 0
      sleep 5
    done
    exit 1
  delegate_to: "{{ groups['master'][0] }}"
  vars:
    ansible_become: false  #อํานาจเยอะกว่า become=false!
  when: node_status.stdout != "Ready"
  retries: 3
  delay: 10
  register: node_ready
  until: node_ready.rc == 0
